version: '3.7'
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:root54321@postgres:5432/postgresDb
      NODE_ENV: development
      PORT: 5000
    ports:
      - '8000:5000'

  postgres:
    image: postgres:13.4
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root54321
      POSTGRES_DB: postgresDb
